### ISSUE TITLE
Next buttons appear at different heights

### ISSUE THREAD

**Issue by ScottIsAFool** [MediaBrowser/Emby.Mobile.Universal#23]
When you click on the next button, the following next button jumps, these should, ideally not "move" between page transitions.

**Comment by 7illusions** [comment]
Fixed in https://github.com/MediaBrowser/Emby.Mobile.Universal/commit/9a2f884f233ae32724f0034a8cb63efe34ad4555

**Comment by Corlas** [comment]
---------- Forwarded message ----------
From: Karla Baldwin <kaybee526.kb@gmail.com>
Date: Sun, Aug 30, 2015 at 2:31 AM
Subject: Re: [Emby.Mobile.Universal] Next buttons appear at different
heights (#23)
To: "MediaBrowser/Emby.Mobile.Universal" <
reply@reply.github.com
>
